import yaml
import os

# ------------------------------------------------------------
# Pfade robust bestimmen
# ------------------------------------------------------------

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
INPUT_FILE = os.path.join(SCRIPT_DIR, "protocol_constants.yaml")
OUTPUT_DIR = os.path.join(SCRIPT_DIR, "generated_constants")

# Mapping: architecture -> output header file
ARCH_TO_FILE = {
    "core":      "protocol_constants_core.h",
    "bridge":    "protocol_constants_bridge.h",
    "signal":    "protocol_constants_signal.h",
    "switch":    "protocol_constants_switch.h",
    "servo":     "protocol_constants_servo.h",
    "can":       "protocol_constants_can.h",
    "maerklin":  "protocol_constants_maerklin.h",
}

HEADER_TEMPLATE = """#pragma once
// ------------------------------------------------------------
// Auto-generated by generate_protocol_headers.py
// DO NOT EDIT MANUALLY
// ------------------------------------------------------------

"""

# ------------------------------------------------------------
# Hilfsfunktion: Headerdatei schreiben
# ------------------------------------------------------------

def write_header_file(filename, constants):
    path = os.path.join(OUTPUT_DIR, filename)
    with open(path, "w") as f:
        f.write(HEADER_TEMPLATE)
        for name, value in constants.items():
            f.write(f"#define {name} {value}\n")
    print(f"✔ erzeugt: {path}")

# ------------------------------------------------------------
# Hauptlogik
# ------------------------------------------------------------

def main():
    # Output-Verzeichnis anlegen
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)

    # YAML laden
    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    constants = data.get("constants", {})

    # Architektur-Sammler
    buckets = {arch: {} for arch in ARCH_TO_FILE.keys()}

    # Konstanten einsortieren
    for name, entry in constants.items():
        value = entry["value"]
        arch = entry["architecture"]

        if arch not in buckets:
            print(f"⚠ Warnung: Unbekannte Architektur '{arch}' bei {name}")
            continue

        buckets[arch][name] = value

    # Headerdateien erzeugen
    for arch, filename in ARCH_TO_FILE.items():
        if buckets[arch]:
            write_header_file(filename, buckets[arch])
        else:
            print(f"⚠ Hinweis: Keine Konstanten für Architektur '{arch}'")

    print("\nFertig! Alle Headerdateien wurden erzeugt.")

# ------------------------------------------------------------
# Start
# ------------------------------------------------------------

if __name__ == "__main__":
    main()
